### ISSUE TITLE
Module Keep rebooting

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/TTGO_TCall#132]
**Describe the bug**
Module keep rebooting after updating thing-speak data.

**Expected behavior**
Module Should update thing-speak/Things-board data if allowed then perform next task.

**Screenshots**
I'm attaching ![image](https://github.com/mhamidjamil/TTGO_TCall/assets/56353262/85179f09-694a-4028-ac3f-84a595eaeafe) i receive when Guru Meditation Error occurs.

**Additional context**
When i disable things-board update it stop happening so there is a bug in things-board update.
#122 failed

**Comment by mhamidjamil** [comment]
It happens due to certain factors 1 is described in [discussion](https://github.com/mhamidjamil/TTGO_TCall/discussions/44) and i think when we use both USB and battery source then it happens.
