### ISSUE TITLE
System is not executing messages (instantly)

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/TTGO_TCall#135]
**Bug description: **
I have send messages to test the flow of [SECO](https://github.com/mhamidjamil/orangePi/issues/2) task which you have created PR hour ago but i got nothing in response.

**To Reproduce**
Send any message (I tried untrained message)

**Expected behavior**
System should forward that message to authorize person and ask what to do with that message. (But in you [case ](https://github.com/mhamidjamil/orangePi/pull/36/commits/99b9e90eb31ac8799ba238fd968ac13a35b897c7) system should reboot if receive [this command: restart op])

**Screenshots**
I'm attaching conversation ![WhatsApp Image 2023-11-16 at 01 47 56_83d745cd](https://github.com/mhamidjamil/TTGO_TCall/assets/56353262/d0c62d91-5853-4d51-8249-c487ce881982)

**Can you please look at the milestone carefully, I think we shouldn't face any errors related to our previous task**

**Comment by mhamidjamil** [comment]
I don't face any issue like this, yesterday i executed restart op and it executed as expected.
