### ISSUE TITLE
battery command not working

### ISSUE THREAD

**Issue by hamidjamil0420** [mhamidjamil/TTGO_TCall#6]
When we send #battery command to fetch current battery status we get wrong response
![Screenshot_2023-07-26-00-17-15-855_com microsoft android smsorganizer](https://github.com/mhamidjamil/TTGO_TCall/assets/116033118/f351b77c-6150-4283-ad45-fbc76ea5b154)

**Comment by mhamidjamil** [comment]
@hamidjamil0420 checkout in this release 4.5.4 (latest code) its fixed now.

**Comment by hamidjamil0420** [comment]
yah now its working fine @mhamidjamil
