### ISSUE TITLE
Unable to boot system

### ISSUE THREAD

**Issue by wasey-rao** [mhamidjamil/TTGO_TCall#86]
**Bug detail**
I have uploaded pre release code Version 5.3.5 12:19 7 September, after that update I'm Getting this error:
`Guru Meditation Error: Core  1 panic'ed (Double exception).`

**To Reproduce**
1. upload version i mentioned 
2. Monitor the Serial Terminal
3. You will see when module connect with WIFI it ran to this mentioned problem.

**Expected behavior**
System should bootup like it was supposed to and update Thing-Speak #84 values and also send the time stamp message to user so user have record that the system booted at this time

**Screenshots**
![image](https://github.com/mhamidjamil/TTGO_TCall/assets/56353262/3571f914-8c70-4953-ae80-e38ce03b4799)

Using Arduino IDE
Version 1.8.19
with this ![image](https://github.com/mhamidjamil/TTGO_TCall/assets/56353262/5e44eb64-04d9-44d5-a86b-8216df61da03)

**Comment by mhamidjamil** [comment]
issue got fixed in #86
