### ISSUE TITLE
Messaging part is not working! 

### ISSUE THREAD

**Issue by mhamidjamil** [mhamidjamil/TTGO_TCall#95]
**Describe the bug**
When module power up or it receive message it is not forwarding it or no message in a day, it is not possible that the module didn't receive any message from company. 

**To Reproduce**
1. Call it or reboot it you ahould get a message but not

**Expected behavior**
When module reboot or recive call it should send a message and yes one more thing also use these WhatsApp messages feature.

**Comment by wasey-rao** [comment]
I have checked, it happened because sim nether have message package nor balance.

**Comment by mhamidjamil** [comment]
I think then #61 part is useless until it can sense that module ran out of balance or package.
create new feature for this issue. so, in future i should not send message when the package date over..
